# For more information: https://laravel.com/docs/sail
services:
    app:
        container_name: ${DOCKER_CONTAINER_NAME:-laravel_multi_factor}
        build:
            context: ./docker/${DOCKER_PHP_VERSION:-8.4}
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-${DOCKER_PHP_VERSION:-8.4}/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './exampleApp:/var/www/html'
            - './.env:/var/www/html/.env'
            - '.:/var/www/package'
        networks:
            - internal
            - shared
        depends_on:
            - mysql
    mysql:
        container_name: laravel-multi-factor-mysql-1
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:-laravel_multi_factor}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - internal
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
networks:
    internal:
        internal: true
    shared:
        external: true
